#!/bin/bash

git clean -dfx

# nix-build --cores 4 . --argstr coqPackages coqPackages_8_10 > log_8_10.txt 2>&1 &
# nix-build --cores 4 . --argstr coqPackages coqPackages_8_11 > log_8_11.txt 2>&1 &
# nix-build --cores 4 . --argstr coqPackages coqPackages_8_12 > log_8_12.txt 2>&1 &
# nix-build --cores 4 . --argstr coqPackages coqPackages_8_13 > log_8_13.txt 2>&1 &
# nix-build --cores 4 . --argstr coqPackages coqPackages_8_14 > log_8_14.txt 2>&1 &
# nix-build --cores 4 . --argstr coqPackages coqPackages_8_15 > log_8_15.txt 2>&1 &

docker run -t coqorg/coq:8.15 bash -c '
    git clone https://github.com/jwiegley/coq-haskell;
    cd coq-haskell;
    opam update;
    opam pin add -n -y -k path coq-haskell .;
    opam install -y -v -j 2 coq-haskell --deps-only;
    opam install -y -v -j 2 coq-haskell;
    cd ..;
    git clone https://github.com/jwiegley/linearscan;
    cd linearscan;
    opam update;
    opam pin add -n -y -k path coq-linearscan .;
    opam install -y -v -j 2 coq-linearscan --deps-only;
    opam install -y -v -j 2 coq-linearscan
'

wait
