# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, transformers, free, hoopl, hspec, hspecExpectations, lensFamilyCore }:

cabal.mkDerivation (self: {
  pname = "linearscan";
  version = "0.3.0.1";
  src = builtins.filterSource (path: type: type != "unknown") ./.;
  buildDepends = [ transformers ];
  testDepends = [ transformers free hoopl hspec hspecExpectations
                  lensFamilyCore ];
  doCheck = true;
  meta = {
    homepage = "http://github.com/jwiegley/linearscan";
    description = "An optimized linear scan register allocator";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
