#!/bin/bash
# If the checkout of linearscan is somewhere other than ~/bae/linearscan
# then set LINSCANDIR
linearscandir=${LINSCANDIR:-$HOME/bae/linearscan}
exec coqtop -I . -I $linearscandir -dont-load-proofs -quality "$@"
